/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\nvm\\v8.9.4\\node_modules\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-31505852",
    path: "/baseComponents/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31505852").then(next)
    },
  },
  {
    path: "/baseComponents/index.html",
    redirect: "/baseComponents/"
  },
  {
    name: "v-04b75e58",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04b75e58").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-795f23b2",
    path: "/baseComponents/base/page1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-795f23b2").then(next)
    },
  },
  {
    name: "v-2bde0687",
    path: "/baseComponents/base/page2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2bde0687").then(next)
    },
  },
  {
    name: "v-d728c232",
    path: "/baseComponents/base/page3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d728c232").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]