/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/baseComponents/",
      "relativePath": "baseComponents/README.md",
      "key": "v-31505852",
      "path": "/baseComponents/"
    },
    {
      "frontmatter": {
        "home": false,
        "heroImage": "/favicon.ico",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present xxxxxx"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-04b75e58",
      "path": "/"
    },
    {
      "title": "项目规范",
      "frontmatter": {},
      "regularPath": "/baseComponents/base/page1.html",
      "relativePath": "baseComponents/base/page1.md",
      "key": "v-795f23b2",
      "path": "/baseComponents/base/page1.html",
      "headers": [
        {
          "level": 2,
          "title": "命名规范",
          "slug": "命名规范"
        },
        {
          "level": 3,
          "title": "文件&文件夹命名",
          "slug": "文件-文件夹命名"
        },
        {
          "level": 3,
          "title": "变量命名",
          "slug": "变量命名"
        },
        {
          "level": 2,
          "title": "编辑器配置",
          "slug": "编辑器配置"
        },
        {
          "level": 2,
          "title": "Vue 组件开发",
          "slug": "vue-组件开发"
        },
        {
          "level": 2,
          "title": "样式",
          "slug": "样式"
        },
        {
          "level": 2,
          "title": "其他",
          "slug": "其他"
        },
        {
          "level": 2,
          "title": "附录",
          "slug": "附录"
        }
      ]
    },
    {
      "title": "工程协作",
      "frontmatter": {},
      "regularPath": "/baseComponents/base/page2.html",
      "relativePath": "baseComponents/base/page2.md",
      "key": "v-2bde0687",
      "path": "/baseComponents/base/page2.html",
      "headers": [
        {
          "level": 2,
          "title": "拉取代码",
          "slug": "拉取代码"
        },
        {
          "level": 2,
          "title": "代码提交",
          "slug": "代码提交"
        },
        {
          "level": 3,
          "title": "\b 1. 本地个人分支提交",
          "slug": "_1-本地个人分支提交"
        },
        {
          "level": 3,
          "title": "\b 2. 合并远程 master 分支最新代码到个人分支",
          "slug": "_2-合并远程-master-分支最新代码到个人分支"
        },
        {
          "level": 3,
          "title": "\b 3. 本地验证",
          "slug": "_3-本地验证"
        },
        {
          "level": 3,
          "title": "\b 4. \b 推送个人分支到远端",
          "slug": "_4-推送个人分支到远端"
        },
        {
          "level": 3,
          "title": "\b 5. \b 合入 master 分支",
          "slug": "_5-合入-master-分支"
        }
      ]
    },
    {
      "title": "本地开发",
      "frontmatter": {},
      "regularPath": "/baseComponents/base/page3.html",
      "relativePath": "baseComponents/base/page3.md",
      "key": "v-d728c232",
      "path": "/baseComponents/base/page3.html",
      "headers": [
        {
          "level": 2,
          "title": "环境配置",
          "slug": "环境配置"
        },
        {
          "level": 2,
          "title": "安装项目依赖",
          "slug": "安装项目依赖"
        },
        {
          "level": 2,
          "title": "启动服务",
          "slug": "启动服务"
        },
        {
          "level": 2,
          "title": "项目结构说明",
          "slug": "项目结构说明"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "前端之路",
        "link": "/baseComponents/"
      },
      {
        "text": "one-monent",
        "link": "/life/"
      },
      {
        "text": "Github",
        "link": "https://github.com/arieltlm/"
      }
    ],
    "sidebar": {
      "/": [
        {
          "title": "布局类组件",
          "collapsable": true,
          "children": [
            "/baseComponents/base/page1",
            "baseComponents/base/page2",
            "baseComponents/base/page3"
          ]
        },
        {
          "title": "可视化组件",
          "collapsable": true,
          "children": []
        },
        {
          "title": "工具类组件",
          "collapsable": true,
          "children": []
        },
        {
          "title": "方法类函数",
          "collapsable": true,
          "children": []
        }
      ],
      "/knowledge/": [
        {
          "title": "CSS知识库",
          "collapsable": false,
          "children": []
        },
        {
          "title": "JS知识库",
          "collapsable": false,
          "children": []
        },
        {
          "title": "node知识库",
          "collapsable": false,
          "children": []
        },
        {
          "title": "vue知识库",
          "collapsable": false,
          "children": []
        }
      ]
    }
  }
}